version: '0.1'

services:

  application:
    image: giovanna0/modulo7:ponderada2
    restart: always
    expose:
      - "5000"
    ports:
      - 5000:5000
    depends_on:
      - db
    container_name: ponderada2

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    expose:
      - "5432"
    ports:
      - 5432:5432